server:
  port: 6789
  servlet:
    context-path: /security

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/security
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

jwt:
  header: Authorization
  secret: kostya
  expiration: 604800
