server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/library
    username: user
    password: password

  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
